services:
  # django-migrations:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: bash -c "python manage.py migrate --noinput"
  #   env_file:
  #     - .env
  #   networks:
  #       - cpass_net

  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    # depends_on:
    #   django-migrations:
    #     condition: service_completed_successfully
    networks:
      - cpass_net
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    environment:
      # DJANGO_SECRET_KEY   : ${DJANGO_SECRET_KEY}
      # DEBUG               : ${DEBUG}
      # DJANGO_LOGLEVEL     : ${DJANGO_LOGLEVEL}
      # DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

      TELEGRAM_BOT_TOKEN  : ${TELEGRAM_BOT_TOKEN}

      # DATABASE_ENGINE     : ${DATABASE_ENGINE}
      # DATABASE_NAME       : ${DATABASE_NAME}
      # DATABASE_USERNAME   : ${DATABASE_USERNAME}

      # DATABASE_PASSWORD   : ${DATABASE_PASSWORD}
      # DATABASE_HOST       : ${DATABASE_HOST}
      # DATABASE_PORT       : ${DATABASE_PORT}
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
      - react_build:/usr/share/nginx/html:ro
    depends_on:
      - backend-app
      - frontend-app
    networks:
      - cpass_net
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  frontend-app:
    build:
      context: ./cpassdemo
      dockerfile: Dockerfile
    container_name: react-app
    volumes:
      - react_build:/app/dist
    command: tail -f /dev/null
    networks:
      - cpass_net
    restart: unless-stopped

networks:
  cpass_net:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  react_build:
