services:
  # django-migrations:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: bash -c "python manage.py migrate --noinput"
  #   env_file:
  #     - .env
  #   networks:
  #       - cpass_net
  backend-app:
    build:
      context: ./django-project
      dockerfile: Dockerfile.dev.local
    container_name: django-app
    volumes:
      - ./django-project:/app
      - ./shared:/shared
    ports:
      - "8000:8000"
    # depends_on:
    #   django-migrations:
    #     condition: service_completed_successfully
    networks:
      - cpass_net
    healthcheck:
      test: ["CMD", "test", "-f", "/shared/.demo_institutions.json"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    environment:
      DJANGO_SETTINGS_MODULE : config.settings.dev
    env_file:
      - .env

  tvet-backend-app:
    build:
      context: ./tvet_django_project
      dockerfile: Dockerfile.dev.local
    container_name: tvet-django-app
    depends_on:
      backend-app:
        condition: service_healthy
    volumes:
      - ./tvet_django_project:/app
      - ./shared:/shared
    ports:
      - "8001:8001"
    networks:
      - cpass_net
    env_file:
      - .env

  frontend-app:
    build:
      context: ./cpassdemo
      dockerfile: Dockerfile.dev.local
    container_name: react-app
    volumes:
      - ./cpassdemo:/app
    ports:
      - "8080:8080"
    # command: tail -f /dev/null
    networks:
      - cpass_net
    restart: 'unless-stopped'

networks:
  cpass_net:
    driver: bridge
