services:
  # django-migrations:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: bash -c "python manage.py migrate --noinput"
  #   env_file:
  #     - .env
  #   networks:
  #       - cpass_net

  backend-app:
    build:
      context: ./django-project
      dockerfile: Dockerfile.dev.local
    container_name: django-app
    volumes:
      - ./django-project:/app
    ports:
      - "8000:8000"
    # depends_on:
    #   django-migrations:
    #     condition: service_completed_successfully
    networks:
      - cpass_net
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    environment:
      # DJANGO_SECRET_KEY   : ${DJANGO_SECRET_KEY}
      # DEBUG               : ${DEBUG}
      # DJANGO_LOGLEVEL     : ${DJANGO_LOGLEVEL}
      # DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

      TELEGRAM_BOT_TOKEN  : ${TELEGRAM_BOT_TOKEN}

      # DATABASE_ENGINE     : ${DATABASE_ENGINE}
      # DATABASE_NAME       : ${DATABASE_NAME}
      # DATABASE_USERNAME   : ${DATABASE_USERNAME}

      # DATABASE_PASSWORD   : ${DATABASE_PASSWORD}
      # DATABASE_HOST       : ${DATABASE_HOST}
      # DATABASE_PORT       : ${DATABASE_PORT}
    env_file:
      - .env

  frontend-app:
    build:
      context: ./cpassdemo
      dockerfile: Dockerfile.dev.local
    container_name: react-app
    volumes:
      - ./cpassdemo:/app
    ports:
      - "8080:8080"
    # command: tail -f /dev/null  # Keep container running
    networks:
      - cpass_net
    restart: unless-stopped

networks:
  cpass_net:
    driver: bridge
