"""
Seed demo data for TVET Dashboard.

Usage:
    python manage.py seed_demo_data
    python manage.py seed_demo_data --from-json /path/to/institutions.json
"""

import json
from django.core.management.base import BaseCommand
from dashboard.models import Institution, StaffUser, CandidateAssessment, UploadBatch
import uuid

# Default demo institutions
# TODO: This need to be removed
DEFAULT_INSTITUTIONS = [
    {
        "institution_code": "KIAMBU001",
        "institution_name": "Kiambu Institute of Science and Technology",
        "institution_type": "TVET",
        "location": "Kiambu, Kenya",
        "country": "Kenya",
        "contact_person": "John Mwangi",
        "contact_email": "admin@kiambu.ac.ke",
        "contact_phone": "+254700000001",
    },
    {
        "institution_code": "NAKURU001",
        "institution_name": "Nakuru Technical Training Institute",
        "institution_type": "TVET",
        "location": "Nakuru, Kenya",
        "country": "Kenya",
        "contact_person": "Jane Wanjiru",
        "contact_email": "admin@nakuru.ac.ke",
        "contact_phone": "+254700000002",
    },
    {
        "institution_code": "MOMBASA001",
        "institution_name": "Mombasa Technical University",
        "institution_type": "TVET",
        "location": "Mombasa, Kenya",
        "country": "Kenya",
        "contact_person": "Ahmed Hassan",
        "contact_email": "admin@mombasa.ac.ke",
        "contact_phone": "+254700000003",
    },
]


class Command(BaseCommand):
    help = "Seed demo data for TVET Dashboard"

    def add_arguments(self, parser):
        parser.add_argument(
            "--from-json",
            type=str,
            help="Import institutions from a JSON file (generated by CPASS seed_demo_institutions --output-json)",
        )
        parser.add_argument(
            "--with-candidates",
            action="store_true",
            help="Create demo candidates/assessments",
        )
        parser.add_argument(
            "--staff-password",
            type=str,
            default="demo123",
            help="Password for demo staff users (default: demo123)",
        )

    def handle(self, *args, **options):
        from_json = options.get("from_json")
        with_candidates = options.get("with_candidates", True)
        staff_password = options.get("staff_password", "demo123")

        self.stdout.write(self.style.NOTICE("Seeding TVET Dashboard demo data..."))
        self.stdout.write("")

        # Load institutions from JSON or use defaults
        if from_json:
            try:
                with open(from_json, "r") as f:
                    institutions_data = json.load(f)
                self.stdout.write(
                    self.style.SUCCESS(
                        f"Loaded {len(institutions_data)} institutions from {from_json}"
                    )
                )
            except Exception as e:
                self.stdout.write(self.style.ERROR(f"Failed to load JSON: {e}"))
                return
        else:
            institutions_data = DEFAULT_INSTITUTIONS
            self.stdout.write(
                self.style.WARNING(
                    "Using default institutions (no --from-json provided)"
                )
            )

        self.stdout.write("")

        created_institutions = []

        for inst_data in institutions_data:
            institution, created = Institution.objects.update_or_create(
                institution_code=inst_data["institution_code"],
                defaults={
                    "institution_name": inst_data["institution_name"],
                    "institution_type": inst_data.get("institution_type", "TVET"),
                    "location": inst_data.get("location", ""),
                    "country": inst_data.get("country", ""),
                    "contact_person": inst_data.get("contact_person", ""),
                    "contact_email": inst_data.get("contact_email", ""),
                    "contact_phone": inst_data.get("contact_phone", ""),
                    "cpass_api_key": inst_data.get("api_key") or "",
                    "cpass_api_active": bool(inst_data.get("api_key")),
                },
            )

            if created:
                self.stdout.write(
                    self.style.SUCCESS(
                        f" Created: {institution.institution_name} ({institution.institution_code})"
                    )
                )
            else:
                self.stdout.write(
                    self.style.WARNING(
                        f" Updated: {institution.institution_name} ({institution.institution_code})"
                    )
                )

            if institution.cpass_api_active:
                self.stdout.write(f'    API Key: {self.style.SUCCESS("configured")}')
            else:
                self.stdout.write(
                    f'    API Key: {self.style.WARNING("not configured")}'
                )

            created_institutions.append(institution)

        self.stdout.write("")

        # Create staff users for each institution
        self.stdout.write(self.style.NOTICE("Creating staff users..."))
        self.stdout.write("")

        for institution in created_institutions:
            # Create admin user
            email = f"admin@{institution.institution_code.lower()}.demo"
            staff, created = StaffUser.objects.get_or_create(
                email=email,
                defaults={
                    "full_name": f"{institution.institution_name} Admin",
                    "institution": institution,
                    "role": "admin",
                    "is_active": True,
                },
            )

            if created:
                staff.set_password(staff_password)
                staff.save()
                self.stdout.write(
                    self.style.SUCCESS(
                        f" Created: {email} (password: {staff_password})"
                    )
                )
            else:
                self.stdout.write(f"  - Exists: {email}")

        self.stdout.write("")

        # Create demo candidates if requested
        if with_candidates and created_institutions:
            self.stdout.write(self.style.NOTICE("Creating demo candidates..."))
            self.stdout.write("")

            institution = created_institutions[0]

            # Get or create demo batch
            batch, _ = UploadBatch.objects.get_or_create(
                batch_id="demo_batch_001",
                defaults={
                    "institution": institution,
                    "source_file_name": "demo_workers.csv",
                    "upload_mode": "demo",
                    "status": "completed",
                    "worker_count": 5,
                    "success_count": 5,
                },
            )

            demo_candidates = [
                {
                    "name": "John Kamau",
                    "phone": "+254711111111",
                    "tier": "silver",
                    "status": "in_progress",
                    "match": 75,
                },
                {
                    "name": "Mary Wanjiku",
                    "phone": "+254711111112",
                    "tier": "gold",
                    "status": "scheduled",
                    "match": 85,
                },
                {
                    "name": "Peter Omondi",
                    "phone": "+254711111113",
                    "tier": "bronze",
                    "status": "identified",
                    "match": 45,
                },
                {
                    "name": "Grace Akinyi",
                    "phone": "+254711111114",
                    "tier": "platinum",
                    "status": "certified",
                    "match": 95,
                },
                {
                    "name": "David Mwangi",
                    "phone": "+254711111115",
                    "tier": "silver",
                    "status": "contacted",
                    "match": 60,
                },
            ]

            for c in demo_candidates:
                assessment, created = CandidateAssessment.objects.get_or_create(
                    institution=institution,
                    worker_phone=c["phone"],
                    defaults={
                        "worker_id": uuid.uuid4(),
                        "worker_name": c["name"],
                        "worker_tier": c["tier"],
                        "assessment_status": c["status"],
                        "certification_match": c["match"],
                        "batch": batch,
                    },
                )

                if created:
                    self.stdout.write(self.style.SUCCESS(f'Created: {c["name"]}'))
                else:
                    self.stdout.write(f'  - Exists: {c["name"]}')

        self.stdout.write("")
        self.stdout.write(self.style.SUCCESS("=" * 50))
        self.stdout.write(self.style.SUCCESS("Demo data seeding complete!"))
        self.stdout.write(self.style.SUCCESS("=" * 50))
        self.stdout.write("")
        self.stdout.write("Login credentials:")
        for institution in created_institutions:
            email = f"admin@{institution.institution_code.lower()}.demo"
            self.stdout.write(f"  {institution.institution_code}:")
            self.stdout.write(f"    Email: {email}")
            self.stdout.write(f"    Password: {staff_password}")
        self.stdout.write("")
